%YAML 1.1
---
application:
  title: "Spleen Segmentation App"
  version: "1.0.0"
  sdk_version: "0.6.0" 
  description: "App per a la segmentació de melsa basada en MONAI Deploy"
  main: "app.py"
  models:
    - name: "spleen_model"
      model: "model.ts"
      format: "torchscript"

resources:
  cpu: 1
  gpu: 1
  memory: "4Gi"